<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/rendering_job.proto

namespace App\Protobuf\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RenderingJobItem</code>
 */
class RenderingJobItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 frame = 1;</code>
     */
    protected $frame = 0;
    /**
     * Generated from protobuf field <code>string working_dir = 2;</code>
     */
    protected $working_dir = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $frame
     *     @type string $working_dir
     * }
     */
    public function __construct($data = NULL) {
        \App\Protobuf\Metadata\RenderingJob::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 frame = 1;</code>
     * @return int
     */
    public function getFrame()
    {
        return $this->frame;
    }

    /**
     * Generated from protobuf field <code>int32 frame = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFrame($var)
    {
        GPBUtil::checkInt32($var);
        $this->frame = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string working_dir = 2;</code>
     * @return string
     */
    public function getWorkingDir()
    {
        return $this->working_dir;
    }

    /**
     * Generated from protobuf field <code>string working_dir = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWorkingDir($var)
    {
        GPBUtil::checkString($var, True);
        $this->working_dir = $var;

        return $this;
    }

}

