<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/rendering_job.proto

namespace App\Protobuf\Metadata;

class RenderingJob
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
‹
protos/rendering_job.proto"6
RenderingJobItem
frame (
working_dir (	B-ÊApp\\Protobuf\\ModelâApp\\Protobuf\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

