<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/rendering_job.proto

namespace GPBMetadata\Protos;

class RenderingJob
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
j
protos/rendering_job.protoApp.Protobuf"6
RenderingJobItem
frame (
working_dir (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

